"use client";
import {useState,useMemo} from 'react';
import {CalendarDays,LayoutDashboard,Users,House,Sparkles,ChartNoAxesCombined,ArrowUpLeft,Plus,Search,ChevronLeft,ChevronRight,Clock,Check,CheckCheck,Phone,MapPin,RefreshCw,SlidersHorizontal,LoaderCircle,Scissors,Hand,Eye,Flower2,Bell,ArrowLeft,CalendarCheck,Download,X, CircleHelp} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {ServiceIcon} from '@/lib/service-icon';
import InstallDesk from './desk/install-desk';
import {useWorkspace,request} from '@/lib/client';
import {day,money,clock,readableDate,team,categories,statusLabel,transitions} from '@/lib/model';
import type {Booking,Service} from '@/lib/model';
const nav=[{id:'overview',label:'نظرة اليوم',icon:LayoutDashboard},{id:'appointments',label:'الحجوزات',icon:CalendarDays},{id:'clients',label:'العميلات',icon:Users},{id:'home',label:'الخدمة المنزلية',icon:House},{id:'services',label:'الخدمات والفريق',icon:Sparkles},{id:'reports',label:'الأداء',icon:ChartNoAxesCombined}];
function Navigation({view,setView}:{view:string;setView:(s:string)=>void}){const {setOpenMobile}=useSidebar();return <Sidebar side="right" className="brand-sidebar"><SidebarHeader className="brand-header"><img src="/brand/logo.png" alt="Madonna Beauty Lounge" className="side-logo"/><span className="side-label">LOUNGE MANAGEMENT</span></SidebarHeader><SidebarContent><p className="nav-caption">مساحة العمل</p><SidebarMenu className="brand-menu">{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>{setView(n.id);setOpenMobile(false);}} className="nav-button"><n.icon size={20}/><span>{n.label}</span>{view===n.id&&<span className="nav-selected"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><a href="/book" target="_blank" rel="noopener" className="side-book"><div className="side-book-icon"><ArrowUpLeft size={20}/></div><span>تجربة العميلة<small>افتحي مساحة الحجز</small></span></a></SidebarContent><SidebarFooter className="brand-footer"><span className="profile-mark">M</span><div><strong>إدارة Madonna</strong><small>عمّان · الدوار السابع</small></div><span className="private-label">خاص</span></SidebarFooter></Sidebar>}
export default function Lounge(){return <SidebarProvider style={{'--sidebar-width':'238px'} as React.CSSProperties}><Workspace/><Toaster position="top-center" dir="rtl"/></SidebarProvider>}
function Workspace(){const {data,setData,error,loading,load,authExpired}=useWorkspace();const [view,setView]=useState('overview'),[date,setDate]=useState(day()),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[staff,setStaff]=useState('all'),[selected,setSelected]=useState<Booking|null>(null),[edit,setEdit]=useState<Service|null>(null),[busy,setBusy]=useState(false),[client,setClient]=useState<string|null>(null),[help,setHelp]=useState(false),[calendar,setCalendar]=useState('timeline');
 const bs=data?.bookings||[],ss=data?.services||[];const today=bs.filter(b=>b.date===date&&b.status!=='cancelled'&&b.status!=='noshow');const pending=bs.filter(b=>b.status==='pending');const total=today.reduce((s,b)=>s+b.total,0),completed=today.filter(b=>b.status==='completed');const rows=bs.filter(b=>(view!=='overview'||b.date===date)&&(view!=='home'||b.mode==='home')&&(filter==='all'||b.status===filter)&&(staff==='all'||b.staff===staff)&&(!search||[b.customer,b.phone,...b.services.map(s=>s.name)].join(' ').includes(search))).sort((a,b)=>view==='overview'?a.start-b.start:b.date.localeCompare(a.date)||a.start-b.start);
 const clients=useMemo(()=>{const m=new Map<string,{name:string;phone:string;visits:number;value:number;last:string;count:number}>();for(const b of bs){const c=m.get(b.phone)||{name:b.customer,phone:b.phone,visits:0,value:0,last:'',count:0};c.count++;if(b.status==='completed'){c.visits++;c.value+=b.total;}if(b.date>c.last)c.last=b.date;m.set(b.phone,c);}return [...m.values()].filter(c=>!search||(c.name+' '+c.phone).includes(search));},[bs,search]);
 const title=nav.find(n=>n.id===view)?.label;
 async function mutate(body:object,success:string){setBusy(true);try{const d=await request(body);setData(d);setSelected(null);setEdit(null);toast.success(success);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 function go(v:string){setView(v);setFilter('all');setSearch('');setStaff('all');}
 function moveDay(n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);setDate(d.toISOString().slice(0,10));}
 function exportCsv(){const csv='\ufeff'+[['التاريخ','الوقت','العميلة','الخدمة','الحالة','المبلغ بالدينار'],...rows.map(b=>[b.date,clock(b.start),b.customer,b.services.map(s=>s.name).join(' + '),statusLabel[b.status],money(b.total)])].map(r=>r.map(c=>'"'+String(c).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='Madonna-Bookings.csv';a.click();URL.revokeObjectURL(url);}
 if(authExpired)return <main className="desk-access"><img src="/brand/logo.png" alt="Madonna"/><h1>نراجع صلاحية الدخول.</h1><p>سجّلي الدخول بحساب الإدارة للمتابعة.</p></main>;
 return <><Navigation view={view} setView={go}/><div className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>Madonna</span><ChevronLeft size={14}/><strong>{title}</strong></div><div className="top-actions"><InstallDesk/><span className="demo-pill">نسخة عرض خاصة</span><button className="icon-button" title="طلبات بانتظار التأكيد" aria-label="طلبات بانتظار التأكيد" onClick={()=>{go('appointments');setFilter('pending');}}><Bell size={19}/>{pending.length>0&&<i>{pending.length}</i>}</button><button className="icon-button" aria-label="حول مساحة العرض" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button></div></header><main className="main-content"><div className="page-heading"><div><p className="eyebrow">MADONNA BEAUTY LOUNGE</p><h1>{view==='overview'?'يومٌ جميل، بكل تفاصيله.':title}</h1><p className="heading-caption">{view==='overview'?readableDate(date):view==='appointments'?'من أول طلب، إلى آخر لمسة.':view==='clients'?'العناية تبدأ بمعرفة كل عميلة.':view==='home'?'تجربة Madonna، حيث تكون العميلة.':view==='services'?'قائمة العناية والفريق الذي يصنعها.':'قراءة واضحة للحجوزات والخدمات المكتملة.'}</p></div><a href="/book" target="_blank" rel="noopener" className="primary-button"><Plus size={18}/>حجز جديد</a></div>
 {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={load}>إعادة المحاولة</button></div>}
 {loading&&!data?<div className="loading-state"><LoaderCircle className="spin"/><p>نرتّب تفاصيل يومك…</p></div>:data&&<>
 {(view==='overview'||view==='reports')&&<div className="metrics"><Metric label="حجوزات اليوم المحدد" value={String(today.length).padStart(2,'0')} unit="موعد" icon={<CalendarDays/>} detail={`${completed.length} خدمة مكتملة`} green/><Metric label="قيمة الحجوزات" value={money(total)} unit="د.أ" icon={<ChartNoAxesCombined/>} detail="تشمل الحجوزات غير المكتملة"/><Metric label="بانتظار التأكيد" value={String(pending.length).padStart(2,'0')} unit="طلب" icon={<Clock/>} detail="كل المواعيد القادمة والمسجلة"/><Metric label="زيارات منزلية اليوم" value={String(today.filter(b=>b.mode==='home').length).padStart(2,'0')} unit="زيارة" icon={<House/>} detail="مع ٣٠ دقيقة انتقال قبل وبعد"/></div>}
 {view==='overview'&&<div className="overview-grid"><section className="panel schedule-panel"><div className="panel-heading"><div><h2>إيقاع اليوم</h2><p>مساحة لكل موعد. وقت لكل تفصيلة.</p></div><div className="date-controls"><button className="icon-button" onClick={()=>moveDay(-1)} aria-label="اليوم السابق"><ChevronRight size={18}/></button><label className="date-input"><CalendarDays size={16}/><input aria-label="تاريخ الجدول" type="date" value={date} onChange={e=>setDate(e.target.value||day())}/></label><button className="icon-button" onClick={()=>moveDay(1)} aria-label="اليوم التالي"><ChevronLeft size={18}/></button></div></div><div className="schedule-toolbar"><Tabs value={calendar} onValueChange={setCalendar} dir="rtl"><TabsList><TabsTrigger value="timeline">الجدول اليومي</TabsTrigger><TabsTrigger value="list">قائمة المواعيد</TabsTrigger></TabsList></Tabs><span className="schedule-key"><i/>حجز مؤكد <i className="sand"/>بانتظار التأكيد</span></div>{calendar==='timeline'?<div className="timeline-scroll"><div className="timeline"><div className="timeline-head"><span>الوقت</span>{team.map(t=><div key={t.id}><span className={'avatar '+t.color}>{t.initial}</span><div><strong>{t.name}</strong><small>{t.role}</small></div></div>)}</div><div className="timeline-body"><div className="time-axis">{Array.from({length:11},(_,i)=><span key={i} style={{top:i*84}}>{clock(600+i*60)}</span>)}</div>{team.map(t=><div className="staff-lane" key={t.id}>{Array.from({length:10},(_,i)=><div className="hour-grid" key={i}/>)}{today.filter(b=>b.staff===t.id).map(b=><button key={b.id} onClick={()=>setSelected(b)} className={'appointment-block '+(b.status==='pending'?'pending':t.color)} style={{top:(b.start-600)/60*84+4,minHeight:Math.max(32,(b.end-b.start)/60*84-8)}}><span className="block-time">{clock(b.start)}<span>{b.mode==='home'?<House size={13}/>:b.status==='completed'?<CheckCheck size={14}/>:null}</span></span><strong>{b.customer}</strong>{b.end-b.start>=60&&<small>{b.services.map(s=>s.name).join(' + ')}</small>}</button>)}</div>)}</div></div></div>:<BookingList rows={rows} select={setSelected}/>}
 <div className="panel-foot"><span>{today.length} مواعيد في هذا اليوم</span><button onClick={()=>go('appointments')}>جميع الحجوزات <ArrowLeft size={15}/></button></div></section><aside className="day-aside"><section className="pending-panel"><div className="section-title"><span className="small-icon"><Bell size={17}/></span><h2>تحتاج لمستك</h2><span className="count">{pending.length}</span></div><p className="subtle">طلبات جديدة بانتظار تأكيد الموعد.</p>{pending.slice(0,3).map(b=><button className="request-card" key={b.id} onClick={()=>setSelected(b)}><div className="request-line"><strong>{b.customer}</strong><ArrowUpLeft size={16}/></div><p>{b.services.map(s=>s.name).join(' + ')}</p><span><Clock size={13}/>{b.date===day()?'اليوم':b.date} · {clock(b.start)}{b.mode==='home'&&' · منزلية'}</span></button>)}{!pending.length&&<div className="mini-empty"><CheckCheck/><p>كل الطلبات مرتّبة.</p></div>}</section><section className="brand-note"><span className="note-eyebrow">THE MADONNA EXPERIENCE</span><h3>عناية تستمر<br/>بعد الموعد.</h3><p>تفاصيل الزيارة محفوظة،<br/>لتبدأ الزيارة القادمة بمعرفة.</p><button onClick={()=>go('clients')}>مساحة العميلات <ArrowUpLeft size={18}/></button><span className="brand-letter" aria-hidden="true">M</span></section><div className="aside-sync"><RefreshCw size={13}/><span>تحديث تلقائي كل ٣٠ ثانية</span></div></aside></div>}
 {(view==='appointments'||view==='home')&&<section className="panel"><div className="listing-toolbar"><label className="search-input"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحثي بالاسم، الهاتف أو الخدمة"/></label><div className="list-filters"><Select value={filter} onValueChange={setFilter} dir="rtl"><SelectTrigger aria-label="حالة الحجز"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">كل الحالات</SelectItem>{Object.entries(statusLabel).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select><Select value={staff} onValueChange={setStaff} dir="rtl"><SelectTrigger aria-label="الأخصائية"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">كل الفريق</SelectItem>{team.map(t=><SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>)}</SelectContent></Select><button className="icon-button" title="تنزيل الحجوزات" aria-label="تنزيل الحجوزات" onClick={exportCsv}><Download size={18}/></button></div></div>{view==='home'&&<div className="home-callout"><House/><div><strong>من الباب إلى آخر لمسة</strong><p>تُحجز ٣٠ دقيقة قبل الزيارة وبعدها لانتقال الأخصائية. العنوان ظاهر داخل تفاصيل الحجز.</p></div></div>}<BookingList rows={rows} select={setSelected}/><div className="panel-foot">{rows.length} حجز</div></section>}
 {view==='clients'&&<section className="panel"><div className="listing-toolbar"><h2>دفتر العميلات <span className="count">{clients.length}</span></h2><label className="search-input"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="اسم العميلة أو رقم الهاتف"/></label></div><div className="client-grid">{clients.map(c=><button className="client-card" key={c.phone} onClick={()=>setClient(c.phone)}><div className="client-card-top"><span className="avatar large">{c.name.slice(0,1)}</span><ArrowUpLeft size={19}/></div><h3>{c.name}</h3><p dir="ltr">{c.phone.startsWith('DEMO')?'عميلة توضيحية':c.phone}</p><div className="client-stats"><span><b>{c.visits}</b> زيارات مكتملة</span><span><b>{money(c.value)}</b> د.أ</span></div><small>آخر موعد مسجل · {c.last}</small></button>)}</div>{!clients.length&&<Empty text="يبدأ دفتر العميلات مع أول حجز."/>}</section>}
 {view==='services'&&<><div className="staff-cards">{team.map(t=><div className="staff-card" key={t.id}><span className={'avatar large '+t.color}>{t.initial}</span><div><h3>{t.name}</h3><p>{t.role}</p></div><span className="staff-count">{today.filter(b=>b.staff===t.id).length} مواعيد اليوم</span></div>)}</div><section className="panel"><div className="panel-heading"><div><h2>قائمة الخدمات</h2><p>الأسعار والمدد الحالية توضيحية وقابلة للتعديل.</p></div><span className="count">{ss.length} خدمات</span></div><div className="service-management">{ss.map(s=><div className="manage-service" key={s.id}><span className="service-icon"><ServiceIcon category={s.category}/></span><div><h3>{s.name}</h3><p>{s.duration} دقيقة · {s.home?'في اللاونج أو المنزل':'داخل اللاونج'}</p></div><span className="service-price">{money(s.price)} <small>د.أ</small></span><span className={'status-badge '+(s.active?'confirmed':'cancelled')}>{s.active?'متاحة':'متوقفة'}</span><button className="icon-button" onClick={()=>setEdit({...s})} aria-label={'تعديل '+s.name}><SlidersHorizontal size={18}/></button></div>)}</div></section></>}
 {view==='reports'&&<div className="reports-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h2>قيمة الخدمات المكتملة</h2><p>آخر ٧ أيام · د.أ · ليست تحصيلات مالية</p></div><ChartNoAxesCombined size={22}/></div><RevenueChart bookings={bs}/></section><section className="panel"><div className="panel-heading"><div><h2>الخدمات الأكثر حجزًا</h2><p>حسب الحجوزات غير الملغاة</p></div></div><div className="ranked-services">{ss.map(s=>({s,n:bs.filter(b=>b.status!=='cancelled'&&b.status!=='noshow'&&b.services.some(x=>x.id===s.id)).length})).sort((a,b)=>b.n-a.n).slice(0,5).map(({s,n},i)=><div key={s.id}><span className="rank-number">0{i+1}</span><span className="service-icon"><ServiceIcon category={s.category}/></span><strong>{s.name}</strong><span>{n} حجوزات</span></div>)}</div></section></div>}
 </>}
 <footer className="workspace-footer"><span>Be Bold. Be Beautiful. <i>Be Madonna.</i></span><span>بيانات وأسعار وفريق توضيحيون · تجربة خاصة</span></footer></main></div>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="detail-dialog" dir="rtl"><DialogTitle>تفاصيل الموعد</DialogTitle><DialogDescription>الحجز وتفاصيل العناية في مكان واحد.</DialogDescription>{selected&&<><div className="booking-person"><span className="avatar large">{selected.customer[0]}</span><div><h2>{selected.customer}</h2><p dir="ltr">{selected.phone.startsWith('DEMO')?'عميلة توضيحية':selected.phone}</p></div><span className={'status-badge '+selected.status}>{statusLabel[selected.status]}</span></div><div className="detail-line"><CalendarDays size={18}/><span>{readableDate(selected.date)}</span></div><div className="detail-line"><Clock size={18}/><span dir="ltr">{clock(selected.start)} — {clock(selected.end)}</span><span>· {team.find(t=>t.id===selected.staff)?.name}</span></div><div className="detail-line"><MapPin size={18}/><span>{selected.mode==='home'?selected.address:'Madonna Beauty Lounge · عمّان'}</span></div><div className="detail-services">{selected.services.map(s=><div key={s.id}><span>{s.name}</span><strong>{money(s.price)} د.أ</strong></div>)}<div className="detail-total"><strong>قيمة الخدمات</strong><strong>{money(selected.total)} د.أ</strong></div></div>{selected.notes&&<p className="booking-note">{selected.notes}</p>}<div className="status-actions">{transitions[selected.status]?.map(st=><button key={st} disabled={busy} onClick={()=>mutate({action:'status',id:selected.id,status:st},'تم تحديث حالة الموعد')} className={st==='cancelled'||st==='noshow'?'secondary-button':'primary-button'}>{st==='confirmed'?'تأكيد الموعد':st==='arrived'?'تسجيل الوصول':st==='completed'?'إنهاء الزيارة':st==='cancelled'?'إلغاء الحجز':'لم تحضر'}{busy&&<LoaderCircle size={16} className="spin"/>}</button>)}</div><p className="fine-print">تحديث الحالة داخل النظام فقط. لم تُرسل رسالة أو تُحصّل دفعة.</p></>}</DialogContent></Dialog>
 <Dialog open={!!edit} onOpenChange={v=>!v&&setEdit(null)}><DialogContent dir="rtl" className="detail-dialog"><DialogTitle>تعديل الخدمة</DialogTitle><DialogDescription>التعديلات تنطبق على الحجوزات الجديدة. الحجوزات السابقة تحتفظ بسعرها ومدتها.</DialogDescription>{edit&&<form onSubmit={e=>{e.preventDefault();mutate({action:'service',service:edit},'تم حفظ الخدمة');}} className="edit-form"><h2>{edit.name}</h2><label>السعر بالدينار<input required type="number" min="0" max="1000" step="0.01" value={edit.price/100} onChange={e=>setEdit({...edit,price:Math.round(Number(e.target.value)*100)})}/></label><label>المدة بالدقائق<input required type="number" min="30" max="240" step="30" value={edit.duration} onChange={e=>setEdit({...edit,duration:Number(e.target.value)})}/></label><label className="switch-label">متاحة للحجز<Switch dir="ltr" checked={!!edit.active} onCheckedChange={v=>setEdit({...edit,active:v?1:0})}/></label><label className="switch-label">متاحة كخدمة منزلية<Switch dir="ltr" checked={!!edit.home} onCheckedChange={v=>setEdit({...edit,home:v?1:0})}/></label><button className="primary-button" disabled={busy}>حفظ التعديلات</button></form>}</DialogContent></Dialog>
 <Dialog open={!!client} onOpenChange={v=>!v&&setClient(null)}><DialogContent className="detail-dialog" dir="rtl"><DialogTitle>{clients.find(c=>c.phone===client)?.name||'سجل العميلة'}</DialogTitle><DialogDescription>تاريخ المواعيد والخدمات.</DialogDescription><div className="history-list">{bs.filter(b=>b.phone===client).map(b=><div key={b.id}><span className={'status-badge '+b.status}>{statusLabel[b.status]}</span><strong>{b.services.map(s=>s.name).join(' + ')}</strong><p>{b.date} · {clock(b.start)} · {money(b.total)} د.أ</p>{b.notes&&<small>{b.notes}</small>}</div>)}</div></DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="detail-dialog" dir="rtl"><DialogTitle>مساحة Madonna الخاصة</DialogTitle><DialogDescription>نسخة عملية لتجربة الحجز والتشغيل قبل اعتماد الصالون.</DialogDescription><p>الحجوزات والتعديلات تُحفظ في مساحتك، ويمكنك العودة إليها من جهاز آخر بعد تسجيل الدخول بالحساب نفسه.</p><p>الأسماء والأسعار ومدد الخدمات وتوزيع الفريق بيانات توضيحية. مواعيد العرض من ١٠ صباحًا إلى ٨ مساءً.</p><p>واتساب والدفع والإشعارات الخارجية غير مفعّلة. تأكيد الموعد هنا لا يرسل طلبًا إلى الصالون الحقيقي.</p><a href="/book" target="_blank" rel="noopener" className="primary-button">تجربة حجز عميلة <ArrowUpLeft size={18}/></a></DialogContent></Dialog></>;
}
function Metric({label,value,unit,icon,detail,green=false}:{label:string;value:string;unit:string;icon:React.ReactNode;detail:string;green?:boolean}){return <article className={'metric '+(green?'metric-green':'')}><div className="metric-top"><span>{label}</span>{icon}</div><div className="metric-value"><b>{value}</b><span>{unit}</span></div><p>{detail}</p></article>}
function Empty({text}:{text:string}){return <div className="empty-state"><CalendarCheck size={30} strokeWidth={1}/><p>{text}</p><a href="/book" target="_blank" rel="noopener">إضافة حجز <Plus size={16}/></a></div>}
function BookingList({rows,select}:{rows:Booking[];select:(b:Booking)=>void}){return !rows.length?<Empty text="لا توجد مواعيد مطابقة لهذا الاختيار."/>:<div className="booking-list">{rows.map(b=><button key={b.id} className="booking-row" onClick={()=>select(b)}><span className="booking-hour"><b>{clock(b.start)}</b><small>{b.date}</small></span><span className={'avatar '+(team.find(t=>t.id===b.staff)?.color||'')}>{b.customer[0]}</span><span className="booking-name"><strong>{b.customer}</strong><small>{b.services.map(s=>s.name).join(' + ')}</small></span><span className="booking-staff">{team.find(t=>t.id===b.staff)?.name}<small>{b.mode==='home'?'زيارة منزلية':'في اللاونج'}</small></span><span className={'status-badge '+b.status}>{statusLabel[b.status]}</span><span className="booking-amount">{money(b.total)} <small>د.أ</small></span><ArrowUpLeft size={18}/></button>)}</div>}
function RevenueChart({bookings}:{bookings:Booking[]}){const days=Array.from({length:7},(_,i)=>{const date=day(i-6);return {date,value:bookings.filter(b=>b.date===date&&b.status==='completed').reduce((v,b)=>v+b.total,0)};});const max=Math.max(100,...days.map(d=>d.value));return <div className="revenue-chart">{days.map(d=><div className="bar-column" key={d.date}><span>{money(d.value)}</span><div className="bar-space"><div style={{height:Math.max(3,d.value/max*170)}}/></div><small>{new Intl.DateTimeFormat('ar-JO',{weekday:'short'}).format(new Date(d.date+'T12:00:00Z'))}</small></div>)}</div>}
