export type Service={id:string;name:string;category:string;price:number;duration:number;home:number;active:number};
export type Booking={id:string;customer:string;phone:string;date:string;start:number;end:number;block_start:number;block_end:number;staff:string;mode:string;status:string;services:Service[];total:number;address:string;notes:string;created:string};
export const categories=[{id:'all',name:'كل الخدمات'},{id:'nails',name:'الأظافر'},{id:'lashes',name:'الرموش'},{id:'hair',name:'الشعر'},{id:'makeup',name:'المكياج'},{id:'care',name:'العناية'}];
export const team=[{id:'sara',name:'سارة',role:'الأظافر والرموش',initial:'س',categories:['nails','lashes'],color:'sage'},{id:'nour',name:'نور',role:'الشعر والمكياج',initial:'ن',categories:['hair','makeup'],color:'rose'},{id:'lara',name:'لارا',role:'العناية والاسترخاء',initial:'ل',categories:['care'],color:'sand'}];
export const sampleServices:Service[]=[{id:'mani',name:'مانيكير كلاسيكي',category:'nails',price:1200,duration:30,home:1,active:1},{id:'pedi',name:'باديكير سبا',category:'nails',price:2000,duration:60,home:1,active:1},{id:'gel',name:'جل للأظافر',category:'nails',price:2500,duration:60,home:1,active:1},{id:'lash',name:'رفع الرموش',category:'lashes',price:3000,duration:60,home:0,active:1},{id:'blow',name:'سشوار وتصفيف',category:'hair',price:1500,duration:30,home:1,active:1},{id:'makeup',name:'مكياج مناسبات',category:'makeup',price:4500,duration:90,home:1,active:1},{id:'facial',name:'جلسة عناية بالبشرة',category:'care',price:3500,duration:60,home:0,active:1},{id:'massage',name:'مساج استرخاء',category:'care',price:3500,duration:60,home:1,active:1},{id:'wax',name:'إزالة الشعر',category:'care',price:1500,duration:30,home:1,active:1}];
export const statusLabel:Record<string,string>={pending:'بانتظار التأكيد',confirmed:'مؤكد',arrived:'وصلت',completed:'مكتمل',cancelled:'ملغي',noshow:'لم تحضر'};
export const activeStatuses=['pending','confirmed','arrived'];
export function day(offset=0){const s=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Amman',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10);}
export function minuteNow(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Amman',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date()).split(':');return +p[0]*60 + +p[1];}
export const money=(n:number)=>(n/100).toLocaleString('en-US',{maximumFractionDigits:2});
export const clock=(n:number)=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
export function readableDate(s:string){return new Intl.DateTimeFormat('ar-JO',{weekday:'long',day:'numeric',month:'long'}).format(new Date(s+'T12:00:00Z'));}
export function eligibleStaff(services:Service[]){return team.filter(t=>services.every(s=>t.categories.includes(s.category)));}
export function availableSlots(bs:Pick<Booking,'date'|'staff'|'block_start'|'block_end'|'status'>[],date:string,staff:string,duration:number,home:boolean,today=day(),now=minuteNow()) {const buffer=home?30:0;return Array.from({length:21},(_,i)=>600+i*30).filter(start=> start+duration<=1200 && !(date===today&&start-buffer<=now) && !bs.some(b=>b.date===date&&b.staff===staff&&b.status!=='cancelled'&&b.status!=='noshow'&&b.block_start<start+duration+buffer&&b.block_end>start-buffer));}
export const transitions:Record<string,string[]>={pending:['confirmed','cancelled'],confirmed:['arrived','cancelled','noshow'],arrived:['completed','cancelled'],completed:[],cancelled:[],noshow:[]};

export function validDate(value:string){const d=new Date(value+"T12:00:00Z");return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===value;}
