"use client";
import {useState,useRef,useEffect} from 'react';
import {ArrowLeft,ArrowRight,Check,Clock,House,MapPin,CalendarDays,Sparkles,LoaderCircle,ChevronLeft,Plus,CheckCheck,ShieldCheck,X,Pause,Play} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {useWorkspace,request} from '@/lib/booking-client';
import {categories,day,readableDate,team,money,clock,eligibleStaff,availableSlots,minuteNow} from '@/lib/model';
import type {Service,Booking} from '@/lib/model';
import {ServiceIcon} from '@/lib/service-icon';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import MadonnaJourney from './journey';
import BookingGallery from './booking-gallery';
import LivingSilk from './living-silk';
import './booking-atelier.css';
import VerifiedContact from './verified-contact';
import {useCustomerIdentity} from '@/lib/customer-client';
import {normalizePhone} from '@/lib/phone';
export default function BookingExperience(){const {data,setData,error,loading,load}=useWorkspace();const [step,setStep]=useState(1),[category,setCategory]=useState('all'),[previewCategory,setPreviewCategory]=useState('nails'),[mode,setMode]=useState('lounge'),[ids,setIds]=useState<string[]>([]),[staff,setStaff]=useState(''),[date,setDate]=useState(minuteNow()>=1140?day(1):day()),[start,setStart]=useState<number|null>(null),[customer,setCustomer]=useState(''),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),[busy,setBusy]=useState(false),[issue,setIssue]=useState(''),[reference,setReference]=useState('');const [confirmed,setConfirmed]=useState<Booking|null>(null);const returnFocus=useRef<HTMLElement|null>(null);
 const identity=useCustomerIdentity();const [verifying,setVerifying]=useState(false);const verified=!!identity.profile&&normalizePhone(phone)===identity.profile.phone;
 useEffect(()=>{if(identity.profile){setCustomer(v=>v||identity.profile!.name);setPhone(v=>v||identity.profile!.phone);}},[identity.profile]);
 const [portalOpen,setPortalOpen]=useState(false),[motion,setMotion]=useState(true),[desktop,setDesktop]=useState(false);
 useEffect(()=>{const query=window.matchMedia('(min-width: 768px)');const update=()=>setDesktop(query.matches);update();query.addEventListener('change',update);return()=>query.removeEventListener('change',update);},[]);
 const requestId=useRef('');const heading=useRef<HTMLHeadingElement>(null);
 const services=data?.services||[],selected=services.filter(s=>ids.includes(s.id)),total=selected.reduce((v,s)=>v+s.price,0),duration=selected.reduce((v,s)=>v+s.duration,0),eligible=eligibleStaff(selected),slots=staff&&duration?availableSlots(data?.bookings||[],date,staff,duration,mode==='home'):[];
 useEffect(()=>{if(!eligible.some(t=>t.id===staff)){setStaff(eligible.length===1?eligible[0].id:'');setStart(null);}},[ids.join(','),mode,services.length]);
 function next(n:number){if((busy&&n!==4)||verifying)return;setIssue('');setStep(n);setTimeout(()=>{heading.current?.focus({preventScroll:true});heading.current?.closest('.booking-work')?.scrollTo({top:0,behavior:'instant'});heading.current?.closest('.booking-layout')?.scrollTo({top:0,behavior:'instant'});},50);}
 useEffect(()=>{const preference=window.matchMedia('(prefers-reduced-motion: reduce)');setMotion(!preference.matches);const update=()=>setMotion(!preference.matches);preference.addEventListener('change',update);return()=>preference.removeEventListener('change',update);},[]);
 function openBooking(cat?:string,place?:string){if(busy)return;returnFocus.current=document.activeElement as HTMLElement;if(place&&place!==mode)modeChange(place);if(cat){setCategory(cat);setPreviewCategory(cat);}else setCategory('all');if(step===4){setConfirmed(null);setIds([]);setStart(null);setReference('');requestId.current='';}setStep(1);setIssue('');setPortalOpen(true);}
 function toggle(s:Service){const next=ids.includes(s.id)?ids.filter(x=>x!==s.id):[...ids,s.id];if(next.length&&eligibleStaff(services.filter(x=>next.includes(x.id))).length===0){setIssue('تحتاج هذه الخدمة أخصائية أخرى. أكملي الموعد الحالي، ثم احجزي لها موعدًا مستقلًا.');return;}setIds(next);setPreviewCategory(s.category);setStart(null);setIssue('');}
 function modeChange(v:string){setMode(v);setIds([]);setStart(null);setStaff('');setIssue('');}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||verifying)return;if(!verified){setIssue('أكّدي رقم واتساب قبل إتمام الحجز.');return;}setBusy(true);setIssue('');if(!requestId.current)requestId.current=crypto.randomUUID();try{const d=await request({action:'book',customer,phone:normalizePhone(phone),date,start,staff,mode,address,ids,requestId:requestId.current});setData(d);setConfirmed(d.receipt||null);setReference((d.bookingId||'').split(':').at(-1)?.slice(0,8).toUpperCase()||'');next(4);}catch(e){setIssue((e as Error).message);request().then(setData).catch(()=>{});}finally{setBusy(false);}}
 return <><MadonnaJourney onBook={openBooking} motion={motion} onMotion={()=>setMotion(v=>!v)} bookingOpen={portalOpen} services={services}/><Dialog open={portalOpen} onOpenChange={v=>{if(!busy&&!verifying)setPortalOpen(v);}}><DialogContent className="booking-portal booking-emerald translate-x-0 translate-y-0" style={{translate:"none",scale:"1",rotate:"none"}} showCloseButton={false} dir="rtl" onCloseAutoFocus={e=>{e.preventDefault();returnFocus.current?.focus({preventScroll:true});}}><DialogTitle className="sr-only">حجز عناية Madonna</DialogTitle><DialogDescription className="sr-only">اختاري الخدمة والأخصائية والموعد، ثم احفظي طلبك في مساحة العرض الخاصة.</DialogDescription><div className="booking-experience" data-step={step} data-motion={motion?'on':'off'}><div className="booking-ambience" aria-hidden="true"><LivingSilk motion={motion} active={portalOpen}/></div><header className="portal-header"><button className="portal-close" disabled={busy||verifying} onClick={()=>setPortalOpen(false)} aria-label="إغلاق الحجز والعودة للتجربة"><X size={21}/><span>عودة للتجربة</span></button><div className="portal-wordmark">MADONNA <small>YOUR PRIVATE RITUAL</small></div><div className="portal-utilities"><span className="portal-location">عمّان <MapPin size={15}/></span><button className="booking-motion" onClick={()=>setMotion(v=>!v)} aria-pressed={!motion} aria-label={motion?'إيقاف الحركة':'تشغيل الحركة'}>{motion?<Pause size={17}/>:<Play size={17}/>}<span>{motion?'إيقاف الحركة':'تشغيل الحركة'}</span></button></div></header><main className="booking-layout"><section className="booking-work" key={step}><div className="booking-steps" aria-label="خطوات الحجز">{['العناية','الموعد','تفاصيلك'].map((label,i)=><div key={label} className={step>i+1?'done':step===i+1?'current':''}><span>{step>i+1?<Check size={14}/>:String(i+1).padStart(2,'0')}</span>{label}{i<2&&<ChevronLeft size={13}/>}</div>)}</div>
 <p className="eyebrow">YOUR MOMENT AT MADONNA</p><h1 ref={heading} tabIndex={-1}>{step===1?'لحظتكِ تبدأ هنا.':step===2?'اختاري لحظتكِ.':step===3?'كل التفاصيل، لكِ.':'موعدكِ، صار أقرب.'}</h1><p className="booking-intro">{step===1?'اختاري الخدمة، واتركي لنا جمال التفاصيل.':step===2?'الأوقات المتاحة حسب مدة العناية والأخصائية.':step===3?'اسمكِ وواتساب. ونحتفظ بالتفاصيل لزيارتك القادمة.':'حُفظ طلبك في مساحة العرض، بانتظار تأكيد الاستقبال.'}</p>
 {!desktop&&step<3&&<BookingGallery category={previewCategory} motion={motion} compact/>}
 {(error||issue)&&<div className="error-banner" role="alert"><span>{issue||error}</span>{error&&<button onClick={load}>حاولي مجددًا</button>}{step===3&&issue.includes('وقت')&&<button onClick={()=>next(2)}>اختيار وقت آخر</button>}</div>}
 {loading&&!data?<div className="loading-state"><LoaderCircle className="spin"/>نجهّز مساحة العناية…</div>:data&&<>
 {step===1&&<><RadioGroup value={mode} onValueChange={modeChange} className="mode-options" dir="rtl" aria-label="مكان الخدمة">{[{id:'lounge',title:'في اللاونج',caption:'تفاصيل العناية في مساحتنا',icon:MapPin},{id:'home',title:'في منزلكِ',caption:'Madonna تصل إليكِ في عمّان',icon:House}].map(x=><label key={x.id} className={mode===x.id?'mode-card selected':'mode-card'}><x.icon size={22}/><div><strong>{x.title}</strong><small>{x.caption}</small></div><RadioGroupItem value={x.id} aria-label={x.title}/></label>)}</RadioGroup><Tabs dir="rtl" value={category} onValueChange={v=>{setCategory(v);if(v!=='all')setPreviewCategory(v);}} className="service-tabs"><TabsList variant="line">{categories.map(c=><TabsTrigger key={c.id} value={c.id}>{c.name}</TabsTrigger>)}</TabsList></Tabs><div className="booking-services">{services.filter(s=>s.active&&(category==='all'||s.category===category)&&(mode==='lounge'||s.home)).map(s=><label className={'choose-service '+(ids.includes(s.id)?'selected':'')} key={s.id}><span className="service-icon"><ServiceIcon category={s.category}/></span><span className="service-description"><strong>{s.name}</strong><small><Clock size={13}/>{s.duration} دقيقة</small></span><span className="service-price">{money(s.price)} <small>د.أ</small></span><Checkbox checked={ids.includes(s.id)} onCheckedChange={()=>toggle(s)} aria-label={s.name}/></label>)}</div>{!services.some(s=>s.active&&(category==='all'||s.category===category)&&(mode==='lounge'||s.home))&&<p className="empty-state">لا توجد خدمات متاحة بهذا الاختيار.</p>}<div className="booking-next"><p>{selected.length?`${selected.length} خدمات · ${duration} دقيقة`:'اختاري الخدمة المناسبة لكِ'}</p><button className="primary-button" disabled={!ids.length} onClick={()=>next(2)}>اختيار الموعد <ArrowLeft size={17}/></button></div></>}
 {step===2&&<><section className="booking-section"><h2>مع من تكون العناية؟</h2><RadioGroup dir="rtl" value={staff} onValueChange={v=>{setStaff(v);setStart(null);}} className="staff-choice" aria-label="اختيار الأخصائية">{eligible.map(t=><label key={t.id} className={'staff-option '+(staff===t.id?'selected':'')}><span className={'avatar '+t.color}>{t.initial}</span><span><strong>{t.name}</strong><small>{t.role}</small></span><RadioGroupItem value={t.id} aria-label={t.name}/></label>)}</RadioGroup></section><section className="booking-section"><div className="section-title"><h2>اليوم المناسب</h2><label className="date-input"><CalendarDays size={16}/><input type="date" min={day()} max={day(60)} aria-label="اختيار تاريخ آخر" value={date} onChange={e=>{setDate(e.target.value||day());setStart(null);}}/></label></div><RadioGroup dir="rtl" value={date} onValueChange={v=>{setDate(v);setStart(null);}} className="day-choice" aria-label="اليوم">{Array.from({length:7},(_,i)=>{const d=day(i);return <label className={'day-option '+(d===date?'selected':'')} key={d}><RadioGroupItem className="sr-only" value={d}/><small>{i===0?'اليوم':new Intl.DateTimeFormat('ar-JO',{weekday:'short'}).format(new Date(d+'T12:00:00Z'))}</small><strong>{Number(d.slice(-2))}</strong></label>})}</RadioGroup></section><section className="booking-section"><h2>الأوقات المتاحة <small>بتوقيت عمّان</small></h2>{!staff?<p className="slot-empty">اختاري الأخصائية لعرض الأوقات.</p>:!slots.length?<p className="slot-empty">لا توجد أوقات تناسب مدة الخدمة. جرّبي يومًا آخر.</p>:<RadioGroup dir="ltr" value={start===null?'':String(start)} onValueChange={v=>setStart(Number(v))} className="slot-grid" aria-label="وقت الموعد">{slots.map(n=><label key={n} className={'time-slot '+(n===start?'selected':'')}><RadioGroupItem className="sr-only" value={String(n)}/>{clock(n)}</label>)}</RadioGroup>}{mode==='home'&&<p className="fine-print">تُضاف ٣٠ دقيقة قبل الزيارة وبعدها لانتقال الأخصائية.</p>}</section><div className="booking-next"><button className="text-button" onClick={()=>next(1)}><ArrowRight size={16}/>الخدمات</button><button className="primary-button" disabled={!staff||start===null||!slots.includes(start)} onClick={()=>next(3)}>متابعة التفاصيل <ArrowLeft size={17}/></button></div></>}
 {step===3&&<form id="madonna-booking-form" onSubmit={submit} className="customer-form"><fieldset className="reservation-fields" disabled={busy}><div className="booking-review"><CalendarDays size={22}/><div><strong>{readableDate(date)}</strong><p>{clock(start||0)} · {duration} دقيقة · {team.find(t=>t.id===staff)?.name}</p></div><button type="button" className="text-button" onClick={()=>next(2)}>تعديل</button></div><VerifiedContact name={customer} phone={phone} onName={setCustomer} onPhone={setPhone} profile={identity.profile} configured={identity.configured} loading={identity.loading} loadError={identity.error} onBusy={setVerifying} onVerified={p=>{identity.setProfile(p);setPhone(p.phone);setCustomer(v=>v||p.name);setIssue('');}}/>{mode==='home'&&<label>عنوانكِ في عمّان<textarea required minLength={8} maxLength={300} autoComplete="street-address" value={address} onChange={e=>setAddress(e.target.value)} placeholder="المنطقة، الشارع، المبنى، الطابق"/></label>}<div className="booking-next"><button type="button" className="text-button" onClick={()=>next(2)}><ArrowRight size={16}/>الموعد</button><button className="primary-button" type="submit" disabled={busy||verifying||!verified}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}{verified?'تأكيد طلب الحجز':'أكّدي واتساب أولًا'}</button></div><p className="fine-print">يُحفظ طلبك للاستقبال بعد تأكيد رقمك. الأسعار والمواعيد بانتظار اعتماد الصالون في نسخة العرض.</p></fieldset></form>}
 {step===4&&<div className="booking-success"><div className="success-mark"><CheckCheck size={35} strokeWidth={1.5}/></div><h2>كل التفاصيل محفوظة.</h2><p>رقم الطلب <strong dir="ltr">MD–{reference}</strong></p><div className="success-receipt"><div><span>العناية</span><strong>{(confirmed?.services||selected).map(s=>s.name).join(' + ')}</strong></div><div><span>الموعد المطلوب</span><strong>{confirmed?.date||date} · {clock(confirmed?.start??start??0)}</strong></div><div><span>المكان</span><strong>{(confirmed?.mode||mode)==='home'?'في المنزل':'في اللاونج'}</strong></div><div><span>قيمة الخدمات</span><strong>{money(confirmed?.total??total)} د.أ</strong></div><div><span>حالة الطلب</span><span className="status-badge pending">بانتظار التأكيد</span></div></div><button className="primary-button" onClick={()=>setPortalOpen(false)}>العودة إلى مادونا <ArrowLeft size={17}/></button><button className="text-button" onClick={()=>{setConfirmed(null);setIds([]);setStart(null);setReference('');requestId.current='';next(1);}}>حجز عناية أخرى <Plus size={16}/></button></div>}
 </>}
 </section><aside className="booking-aside">{desktop&&<BookingGallery category={previewCategory} motion={motion}/>}<div className="appointment-summary"><div className="section-title"><h2>لحظتكِ، بتفاصيلها</h2><Sparkles size={18}/></div>{(step===4&&confirmed?confirmed.services:selected).length?<>{(step===4&&confirmed?confirmed.services:selected).map(s=><div className="summary-service" key={s.id}><span>{s.name}<small>{s.duration} دقيقة</small></span><strong>{money(s.price)} <small>د.أ</small></strong></div>)}<div className="summary-total"><span>قيمة الخدمات</span><strong>{money(step===4&&confirmed?confirmed.total:total)} <small>د.أ</small></strong></div><p className="fine-print">{mode==='home'?'أي رسوم انتقال تحتاج اعتماد الصالون قبل التأكيد.':'السعر المعروض توضيحي لتجربة النظام.'}</p></>:<p className="summary-empty">تبدأ لحظتكِ باختيار العناية.</p>}<div className="summary-location">{mode==='home'?<House size={16}/>:<MapPin size={16}/>}<span>{mode==='home'?'خدمة منزلية · عمّان':'Madonna Beauty Lounge · عمّان'}</span></div></div></aside></main>{step<4&&<div className="booking-mobile-dock">
 {step>1&&<button className="dock-back" type="button" disabled={busy||verifying} onClick={()=>next(step-1)} aria-label="العودة للخطوة السابقة"><ArrowRight size={18}/></button>}
 <div className="dock-summary"><span>{step===1?(ids.length?`${ids.length} خدمات · ${duration} دقيقة`:'اختاري عنايتكِ'):step===2?(start===null?'اختاري الوقت':clock(start)):'قيمة الخدمات'}</span><strong>{money(total)} <small>د.أ</small></strong></div>
 {step===1?<button className="primary-button" disabled={!ids.length||loading||busy} onClick={()=>next(2)}>اختيار الموعد <ArrowLeft size={16}/></button>:step===2?<button className="primary-button" disabled={!staff||start===null||!slots.includes(start)||busy} onClick={()=>next(3)}>التفاصيل <ArrowLeft size={16}/></button>:<button className="primary-button" form="madonna-booking-form" type="submit" disabled={busy||verifying||!verified}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>}{verified?'تأكيد الحجز':'أكّدي واتساب'}</button>}
 </div>}<div className="portal-demo"><ShieldCheck size={13}/><span>عرض خاص · الأسعار والفريق بانتظار اعتماد مادونا</span></div></div></DialogContent></Dialog></>
}
