"use client";
import {useEffect,useState} from 'react';
import {ShieldCheck,Plus,LoaderCircle} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {team} from '@/lib/model';
import type {DeskMember} from '@/lib/desk-access';
const blank:DeskMember={name:'',email:'',role:'reception',staffId:null,active:1};
export default function TeamAccess({online}:{online:boolean}){
 const [members,setMembers]=useState<DeskMember[]>([]),[edit,setEdit]=useState<DeskMember|null>(null),[existing,setExisting]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/desk/team',{cache:'no-store'});const d=await r.json() as {members:DeskMember[];error?:string};if(!r.ok)throw new Error(d.error||'تعذّر تحميل الفريق.');setMembers(d.members);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!online||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/desk/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)}),d=await r.json() as {members:DeskMember[];error?:string};if(!r.ok)throw new Error(d.error||'تعذّر الحفظ.');setMembers(d.members);setEdit(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel desk-team-panel"><div className="panel-heading"><div><h2>حسابات الموظفات</h2><p>المدير يتحكم بمن يدخل، وما يمكنه رؤيته.</p></div><button className="primary-button" disabled={!online} onClick={()=>{setExisting(false);setEdit({...blank});setError('');}}><Plus size={18}/>إضافة موظفة</button></div><div className="desk-role-guide"><p><ShieldCheck size={18}/><strong>الاستقبال</strong><span>الحجوزات، التأكيد، وملفات العميلات.</span></p><p><ShieldCheck size={18}/><strong>الأخصائية</strong><span>مواعيدها فقط، وتحديث حالة الزيارة.</span></p></div>
 {error&&!edit&&<div className="error-banner" role="alert">{error}<button onClick={()=>void load()}>إعادة المحاولة</button></div>}{loading?<div className="loading-state"><LoaderCircle className="spin"/></div>:<div className="desk-members">{members.map(m=><button className="desk-member" key={m.email} onClick={()=>{setExisting(true);setEdit({...m});setError('');}}><span className="avatar">{m.name[0]}</span><span><strong>{m.name}</strong><small dir="ltr">{m.email}</small></span><span>{m.role==='reception'?'الاستقبال':team.find(t=>t.id===m.staffId)?.name+' · أخصائية'}</span><b className={'status-badge '+(m.active?'confirmed':'cancelled')}>{m.active?'مفعّل':'موقوف'}</b></button>)}{!members.length&&<div className="empty-state"><ShieldCheck size={30}/><p>حساب المدير هو الحساب الوحيد حاليًا.</p><span>أضيفي الموظفات المصرّح لهنّ باستخدام التطبيق.</span></div>}</div>}
 <p className="desk-access-note">إضافة البريد تحدّد صلاحية العمل داخل التطبيق، ولا ترسل دعوة. يجب أيضًا إتاحة فتح التطبيق للحساب من إعدادات المشاركة الخاصة.</p>
 <Dialog open={!!edit} onOpenChange={v=>!v&&!busy&&setEdit(null)}><DialogContent className="detail-dialog" dir="rtl"><DialogTitle>{existing?'صلاحية الموظفة':'إضافة موظفة'}</DialogTitle><DialogDescription>استخدمي البريد نفسه الذي تسجّل به الموظفة دخولها.</DialogDescription>{edit&&<form className="staff-booking-form" onSubmit={save}><label>الاسم<input required minLength={2} maxLength={80} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>البريد الإلكتروني<input type="email" dir="ltr" required disabled={existing} value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/></label><label>الصلاحية<Select dir="rtl" value={edit.role} onValueChange={v=>setEdit({...edit,role:v as DeskMember['role'],staffId:v==='specialist'?(edit.staffId||team[0].id):null})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="reception">الاستقبال</SelectItem><SelectItem value="specialist">الأخصائية · مواعيدها فقط</SelectItem></SelectContent></Select></label>{edit.role==='specialist'&&<label>جدول الأخصائية المرتبط<Select dir="rtl" value={edit.staffId||''} onValueChange={v=>setEdit({...edit,staffId:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{team.map(t=><SelectItem key={t.id} value={t.id}>{t.name} · {t.role}</SelectItem>)}</SelectContent></Select></label>}<label className="switch-label">السماح بالدخول<Switch dir="ltr" checked={!!edit.active} onCheckedChange={v=>setEdit({...edit,active:v?1:0})}/></label>{error&&<p role="alert" className="error-banner">{error}</p>}<button className="primary-button" disabled={busy||!online}>{busy&&<LoaderCircle size={18} className="spin"/>}حفظ الصلاحية</button></form>}</DialogContent></Dialog>
 </section>;
}
