import {sqliteTable,text,integer,primaryKey,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const workspaces=sqliteTable('workspaces',{owner:text('owner').primaryKey(),created:text('created').notNull()});
export const customers=sqliteTable('customers',{owner:text('owner').notNull(),userId:text('user_id').notNull(),name:text('name').notNull(),phone:text('phone').notNull(),verifiedAt:text('verified_at').notNull()},t=>[primaryKey({columns:[t.owner,t.userId]}),uniqueIndex('customers_owner_phone_unique').on(t.owner,t.phone)]);
export const verificationChallenges=sqliteTable('verification_challenges',{id:text('id').primaryKey(),owner:text('owner').notNull(),userId:text('user_id').notNull(),phone:text('phone').notNull(),name:text('name').notNull(),providerSid:text('provider_sid').notNull(),expires:integer('expires').notNull(),attempts:integer('attempts').notNull(),status:text('status').notNull()},t=>[index('verification_owner_user').on(t.owner,t.userId),index('verification_expiry').on(t.owner,t.expires)]);
export const verificationDispatches=sqliteTable('verification_dispatches',{id:text('id').primaryKey(),owner:text('owner').notNull(),userHash:text('user_hash').notNull(),phoneHash:text('phone_hash').notNull(),created:integer('created').notNull()},t=>[index('dispatch_owner_created').on(t.owner,t.created),index('dispatch_user_created').on(t.owner,t.userHash,t.created),index('dispatch_phone_created').on(t.owner,t.phoneHash,t.created)]);
export const services=sqliteTable('services',{owner:text('owner').notNull(),id:text('id').notNull(),name:text('name').notNull(),category:text('category').notNull(),price:integer('price').notNull(),duration:integer('duration').notNull(),home:integer('home').notNull(),active:integer('active').notNull()},t=>[primaryKey({columns:[t.owner,t.id]})]);
export const bookings=sqliteTable('bookings',{id:text('id').primaryKey(),owner:text('owner').notNull(),customer:text('customer').notNull(),phone:text('phone').notNull(),date:text('date').notNull(),start:integer('start').notNull(),end:integer('end').notNull(),blockStart:integer('block_start').notNull(),blockEnd:integer('block_end').notNull(),staff:text('staff').notNull(),mode:text('mode').notNull(),status:text('status').notNull(),services:text('services').notNull(),total:integer('total').notNull(),address:text('address').notNull(),notes:text('notes').notNull(),created:text('created').notNull()},t=>[index('idx_bookings_owner_day_staff').on(t.owner,t.date,t.staff)]);

export const deskMembers=sqliteTable('desk_members',{owner:text('owner').notNull(),email:text('email').notNull(),userId:text('user_id'),name:text('name').notNull(),role:text('role').notNull(),staffId:text('staff_id'),active:integer('active').notNull(),created:text('created').notNull()},t=>[primaryKey({columns:[t.owner,t.email]}),uniqueIndex('desk_members_owner_user').on(t.owner,t.userId)]);
